apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2020-05-06 18:01:57 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-05-06 18:00:44 +0000 UTC
    openshift.io/deployer-pod.name: cakephp-mysql-example-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: cakephp-mysql-example
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"cakephp-mysql-example","namespace":"4e41-yaml-app","selfLink":"/apis/apps.openshift.io/v1/namespaces/4e41-yaml-app/deploymentconfigs/cakephp-mysql-example","uid":"12c384ba-8fc3-11ea-b451-0a580a80011a","resourceVersion":"415390575","generation":2,"creationTimestamp":"2020-05-06T17:57:38Z","labels":{"app":"cakephp-mysql-example","template":"cakephp-mysql-example"},"annotations":{"description":"Defines how to deploy the application server","openshift.io/generated-by":"OpenShiftNewApp","template.alpha.openshift.io/wait-for-ready":"true"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600,"pre":{"failurePolicy":"Retry","execNewPod":{"command":["./migrate-database.sh"],"containerName":"cakephp-mysql-example"}}},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["cakephp-mysql-example"],"from":{"kind":"ImageStreamTag","namespace":"4e41-yaml-app","name":"cakephp-mysql-example:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/4e41-yaml-app/cakephp-mysql-example@sha256:004f5b22c337918ec748e8d38717a02a9595c9f86365c1ebd63548660b1df632"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"name":"cakephp-mysql-example"},"template":{"metadata":{"name":"cakephp-mysql-example","creationTimestamp":null,"labels":{"name":"cakephp-mysql-example"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"cakephp-mysql-example","image":"image-registry.openshift-image-registry.svc:5000/4e41-yaml-app/cakephp-mysql-example@sha256:004f5b22c337918ec748e8d38717a02a9595c9f86365c1ebd63548660b1df632","ports":[{"containerPort":8080,"protocol":"TCP"}],"env":[{"name":"DATABASE_SERVICE_NAME","value":"mysql"},{"name":"DATABASE_ENGINE","value":"mysql"},{"name":"DATABASE_NAME","value":"default"},{"name":"DATABASE_USER","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-example","key":"database-user"}}},{"name":"DATABASE_PASSWORD","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-example","key":"database-password"}}},{"name":"CAKEPHP_SECRET_TOKEN","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-example","key":"cakephp-secret-token"}}},{"name":"CAKEPHP_SECURITY_SALT","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-example","key":"cakephp-security-salt"}}},{"name":"OPCACHE_REVALIDATE_FREQ","value":"2"}],"resources":{"limits":{"memory":"512Mi"}},"livenessProbe":{"httpGet":{"path":"/health.php","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":3,"periodSeconds":60,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/health.php","port":8080,"scheme":"HTTP"},"initialDelaySeconds":3,"timeoutSeconds":3,"periodSeconds":60,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-05-06T17:57:38Z","lastTransitionTime":"2020-05-06T17:57:38Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: "2020-05-06T18:00:44Z"
  generation: 2
  labels:
    app: cakephp-mysql-example
    openshift.io/deployment-config.name: cakephp-mysql-example
    template: cakephp-mysql-example
  name: cakephp-mysql-example-1
  namespace: 4e41-yaml-app
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: cakephp-mysql-example
    uid: 12c384ba-8fc3-11ea-b451-0a580a80011a
  resourceVersion: "415391854"
  selfLink: /api/v1/namespaces/4e41-yaml-app/replicationcontrollers/cakephp-mysql-example-1
  uid: 8178caf2-8fc3-11ea-a595-02fdb1202f5a
spec:
  replicas: 1
  selector:
    deployment: cakephp-mysql-example-1
    deploymentconfig: cakephp-mysql-example
    name: cakephp-mysql-example
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: cakephp-mysql-example
        openshift.io/deployment.name: cakephp-mysql-example-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: cakephp-mysql-example-1
        deploymentconfig: cakephp-mysql-example
        name: cakephp-mysql-example
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: mysql
        - name: DATABASE_ENGINE
          value: mysql
        - name: DATABASE_NAME
          value: default
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: cakephp-mysql-example
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: cakephp-mysql-example
        - name: CAKEPHP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: cakephp-secret-token
              name: cakephp-mysql-example
        - name: CAKEPHP_SECURITY_SALT
          valueFrom:
            secretKeyRef:
              key: cakephp-security-salt
              name: cakephp-mysql-example
        - name: OPCACHE_REVALIDATE_FREQ
          value: "2"
        image: image-registry.openshift-image-registry.svc:5000/4e41-yaml-app/cakephp-mysql-example@sha256:004f5b22c337918ec748e8d38717a02a9595c9f86365c1ebd63548660b1df632
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: cakephp-mysql-example
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
